[package]
name = "x11-stresstest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libscreenshot = { path = "../", default-features = false, features = ["linux"] }